### ISSUE TITLE
use inet_pton in socket pool breaks on FreeBSD

### ISSUE THREAD

**Issue by dch** [h2o/h2o#211]
93c0c2e5188f211036c263a32b2c276768150183 is the first bad commit after bisecting v1.0.1 (good) to v1.1.0, FreeBSD 10.1R-p5 amd64:

```
In file included from /ramdisk/h2o/lib/core/config.c:25:
In file included from /ramdisk/h2o/include/h2o.h:41:
In file included from /ramdisk/h2o/include/h2o/http1client.h:31:
/ramdisk/h2o/include/h2o/socketpool.h:44:32: error: field has incomplete type 'struct sockaddr_in'
            struct sockaddr_in sin;
                               ^
/ramdisk/h2o/include/h2o/socketpool.h:44:20: note: forward declaration of 'struct sockaddr_in'
            struct sockaddr_in sin;
                   ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /ramdisk/h2o
*** Error code 1

Stop.
make[1]: stopped in /ramdisk/h2o
*** Error code 1

Stop.
make: stopped in /ramdisk/h2o
dch   /r/h2o git:remotes/origin/kazuho/async-lookup2:bisect ❯❯❯git bisect bad                                                                            ⏎
93c0c2e5188f211036c263a32b2c276768150183 is the first bad commit
commit 93c0c2e5188f211036c263a32b2c276768150183
Author: Kazuho Oku <kazuhooku@gmail.com>
Date:   Thu Mar 5 16:31:44 2015 +0900

    use inet_pton in socket pool

:040000 040000 30d2c038b20e5c6b7624cab2fba21413d2facde7 dfedb6c89459931be4f5e05a913719db2505e747 M      include
:040000 040000 5e5466cadf226e97433552ee02cfdae5e4c68bc9 50b202c51cea79a1f9a7636b14d6bae6f5943a86 M      lib
dch   /r/h2o git:bisect/bad:bisect ❯❯❯
```

**Comment by syohex** [comment]
`<netinet/in.h>` should be included for using `struct sockaddr_in`.
I confirmed build is successful with following change and I sent PR(#212)

```diff
diff --git a/include/h2o/socketpool.h b/include/h2o/socketpool.h
index f8a06ff..91069c9 100644
--- a/include/h2o/socketpool.h
+++ b/include/h2o/socketpool.h
@@ -26,6 +26,7 @@
 extern "C" {
 #endif
 
+#include <netinet/in.h>
 #include <arpa/inet.h>
 #include <pthread.h>
 #include "h2o/linklist.h"
```

**Comment by dch** [comment]
LGTM nice work @syohex works here too - thankyou!

**Comment by kazuho** [comment]
@dch @syohex Thank you for reporting and fixing the issue.

I have setup a FreeBSD virtual machine for myself so that it would not happen again.  However I am seeing test failures on the environment (likely due to shortage of resource allocated to the VM).  I will ship 1.1.1 once I am certain that there are no issues running H2O on FreeBSD.

**Comment by kazuho** [comment]
FYI I have shipped 1.1.1 along with the fix.

No other issues were found on FreeBSD; I have fixed the tests to conserve less memory so that they would run fine on the operating system.

@dch It would be great if you could update the ports (on the assumption that you are taking care of it).  Thank you for the work!
