### ISSUE TITLE
FreeBSD 12.1 : h2o doesn't build with LibreSSL libressl-3.0.2

### ISSUE THREAD

**Issue by UlasSAYGINIM** [h2o/h2o#2218]
Hi ,

I am trying to install on VM , with 16GB ram , 8 core CPU,
FreeBSD 12.1 and latest port snapshot for NOW.
before installation , freebsd system updated.
for Every dependency ports , default options are selected.

after  # make install clean, 
you will see the error below.

/etc/make.conf

CPUTYPE?=native

CFLAGS=-O2 -pipe -fno-strict-aliasing

COPTFLAGS=\$CFLAGS

MK_PROFILE=no

DEFAULT_VERSIONS+=ssl=libressl python=3.8 python2=2.7 python3=3.8 php=7.4 pgsql=12 mysql=5.7

OPTIONS_SET+=ICONV
OPTIONS_UNSET+=CUPS DEBUG DOCS FONTCONFIG NLS X11 MAN EXAMPLES MAN3
WITHOUT_MODULES=sound ntfs linux
WITHOUT=X11 MAN MAN3 MANPAGES EXAMPLES DOCS

ftp_curl_UNSET=   TLS_SRP

security_p5-GSSAPI_SET     = GSSAPI_MIT
OPTIONS_UNSET             += GSSAPI_BASE
OPTIONS_SET               += GSSAPI_NONE

config File /etc/src.conf

WITHOUT_ATM=YES
WITHOUT_BLUETOOTH=YES
WITHOUT_DICT=YES
WITHOUT_EXAMPLES=YES
WITHOUT_GAMES=YES
WITHOUT_IPFILTER=YES
WITHOUT_HTML=YES
WITHOUT_LPR=YES§
WITHOUT_NDIS=YES
WITHOUT_MAN=YES
WITHOUT_MANPAGES=YES
WITHOUT_MAN_UTILS=YES
WITHOUT_PROFILE=YES
WITHOUT_WIRELESS=YES
WITHOUT_WIRELESS_SUPPORT=YES
WITHOUT_WPA_SUPPLICANT_EAPOL=YES
-----------------------
### after make install clean ####

the error is below.

-------------------- ERROR ------------------
/h2o/work/h2o-2.2.6/src/main.c
--- CMakeFiles/h2o.dir/deps/neverbleed/neverbleed.c.o ---
/usr/ports/www/h2o/work/h2o-2.2.6/deps/neverbleed/neverbleed.c:635:13: error: static declaration of 'RSA_get0_key' follows non-static declaration
static void RSA_get0_key(const RSA *rsa, const BIGNUM **n, const BIGNUM **e, const BIGNUM **d)
            ^
/usr/local/include/openssl/rsa.h:399:6: note: previous declaration is here
void RSA_get0_key(const RSA *r, const BIGNUM **n, const BIGNUM **e,
     ^
/usr/ports/www/h2o/work/h2o-2.2.6/deps/neverbleed/neverbleed.c:650:12: error: static declaration of 'RSA_set0_key' follows non-static declaration
static int RSA_set0_key(RSA *rsa, BIGNUM *n, BIGNUM *e, BIGNUM *d)
           ^
/usr/local/include/openssl/rsa.h:401:5: note: previous declaration is here
int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d);
    ^
/usr/ports/www/h2o/work/h2o-2.2.6/deps/neverbleed/neverbleed.c:666:13: error: static declaration of 'RSA_set_flags' follows non-static declaration
static void RSA_set_flags(RSA *r, int flags)
            ^
/usr/local/include/openssl/rsa.h:409:6: note: previous declaration is here
void RSA_set_flags(RSA *r, int flags);
     ^
3 errors generated.
*** [CMakeFiles/h2o.dir/deps/neverbleed/neverbleed.c.o] Error code 1

make[4]: stopped in /usr/ports/www/h2o/work/.build
1 error

make[4]: stopped in /usr/ports/www/h2o/work/.build
*** [CMakeFiles/h2o.dir/all] Error code 2

make[3]: stopped in /usr/ports/www/h2o/work/.build
1 error

make[3]: stopped in /usr/ports/www/h2o/work/.build
*** [all] Error code 2

make[2]: stopped in /usr/ports/www/h2o/work/.build
1 error

make[2]: stopped in /usr/ports/www/h2o/work/.build
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/www/h2o
*** Error code 1

Stop.
make: stopped in /usr/ports/www/h2o

---------------------

Ports Options : 

===> The following configuration options are available for h2o-2.2.6 and its dependencies
===> The following configuration options are available for h2o-2.2.6:
     DOCS=off: Build and/or install documentation
     MRUBY=on: Build with embedded mruby handler support
===> Use 'make config' to modify these settings
===> The following configuration options are available for pkg-1.12.0:
     DOCS=off: Build and/or install documentation
===> Use 'make config' to modify these settings
===> The following configuration options are available for ruby-2.6.5,1:
     CAPIDOCS=off: Build and install C API documents
     DEBUG=off: Build with debugging support
     DOCS=off: Build and/or install documentation
     EXAMPLES=off: Build and/or install examples
     GMP=off: Use GMP to accelerate Bignum operations
     RDOC=on: Build and install Rdoc indexes
====> Which line editing lib to use: you have to select exactly one of them
     LIBEDIT=on: Use libedit
     READLINE=off: Use libreadline
===> Use 'make config' to modify these settings
===> The following configuration options are available for gmake-4.2.1_3:
     NLS=off: Native Language Support
===> Use 'make config' to modify these settings
===> The following configuration options are available for m4-1.4.18_1,1:
     EXAMPLES=off: Build and/or install examples
     LIBSIGSEGV=off: Use alternative page fault handler (GNU libsigsegv)
===> Use 'make config' to modify these settings
===> The following configuration options are available for texinfo-6.7_1,1:
     NLS=off: Native Language Support
===> Use 'make config' to modify these settings
===> The following configuration options are available for help2man-1.47.11:
     NLS=off: Native Language Support
===> Use 'make config' to modify these settings
===> The following configuration options are available for perl5-5.30.1:
     DEBUG=off: Build with debugging support
     DOT_INC=off: Add '.' to @INC (unsafe)
     DTRACE=on: Build with DTrace probes
     GDBM=off: GDBM_File extension
     MULTIPLICITY=on: Use multiplicity
     PERL_64BITINT=on: Use 64 bit integers (on i386)
     PERL_MALLOC=off: Use Perl malloc
     SITECUSTOMIZE=off: Run-time customization of @INC
     THREADS=on: Build threaded perl
===> Use 'make config' to modify these settings
===> The following configuration options are available for p5-Locale-libintl-1.31:
     NLS=off: Native Language Support
===> Use 'make config' to modify these settings
===> The following configuration options are available for libiconv-1.14_11:
     DOCS=off: Build and/or install documentation
     ENCODINGS=on: Include extra character sets
     PATCHES=off: Apply patches to fix CP932, add EUCJP-MS
===> Use 'make config' to modify these settings
===> The following configuration options are available for automake-1.16.1_2:
     DOCS=off: Build and/or install documentation
===> Use 'make config' to modify these settings
===> The following configuration options are available for tcl86-8.6.10:
     DEBUG=off: Build with debugging support
     DTRACE=on: Build with DTrace probes
     TCLMAN=on: Install Tcl function manpages
     THREADS=on: Threading support
     TZDATA=on: Install Tcl timezone data
===> Use 'make config' to modify these settings
===> The following configuration options are available for libressl-3.0.2:
     MAN3=off: Install API manpages (section 3)
     NC=on: Install TLS-enabled netcat
===> Use 'make config' to modify these settings
===> The following configuration options are available for pkgconf-1.6.3,1:
     DOCS=off: Build and/or install documentation
===> Use 'make config' to modify these settings
===> The following configuration options are available for kyua-0.13_4,3:
     DOCS=off: Build and/or install documentation
     EXAMPLES=off: Build and/or install examples
     TEST=on: Build and/or run tests
===> Use 'make config' to modify these settings
===> The following configuration options are available for atf-0.21:
     DOCS=off: Build and/or install documentation
     TEST=on: Build and/or run tests
===> Use 'make config' to modify these settings
===> The following configuration options are available for lutok-0.4_7:
     DOCS=off: Build and/or install documentation
     EXAMPLES=off: Build and/or install examples
     TEST=on: Build and/or run tests
===> Use 'make config' to modify these settings
===> The following configuration options are available for sqlite3-3.30.1:
     ARMOR=off: Detect misuse of the API
     DBPAGE=off: Enable DBPAGE Virtual Table
     DBSTAT=on: Enable DBSTAT Virtual Table
     DIRECT_READ=off: File is read directly from disk
     DQS=on: Double-quoted String Literals
     EXTENSION=on: Allow loadable extensions
     FTS3_TOKEN=on: Enable two-args version fts3_tokenizer
     FTS4=on: Enable FTS3/4 (Full Text Search) module
     FTS5=on: Enable version 5 full-text search engine
     LIKENOTBLOB=off: LIKE does not match blobs
     MEMMAN=off: Allow it to release unused memory
     METADATA=on: Enable column metadata
     NORMALIZE=off: Enable normalized sql function
     NULL_TRIM=off: Omits NULL columns at the ends of rows
     RBU=off: Enable the resumable bulk update
     SECURE_DELETE=on: Overwrite deleted information with zeros
     SORT_REF=off: To use references in the sorter
     STMT=off: Prepared statement scan status
     STSHELL=on: Statically link libsqlite3 into shell
     THREADS=on: Threading support
     UNKNOWN_SQL=off: Suppress unknown function errors
     UNLOCK_NOTIFY=on: Enable notification on unlocking
     URI=on: Enable use the URI filename
     URI_AUTHORITY=off: Allow convert URL into a UNC
====> Optional extensions
     JSON1=off: Enable the JSON1 extension
     SESSION=off: Enable the session extension
====> Optional functions
     OFFSET=off: Enable sqlite_offset() returning record's file offset
     SER1=off: Enable the sqlite3_[de]serialize() interface
     SOUNDEX=off: Enable the soundex() SQL function
====> Unicode support
     ICU=off: Unicode support via ICU
     UNICODE61=on: Unicode Version 6.1 tokenizer
====> Index type for range queries
     RTREE=on: Enable R*Tree module
     RTREE_INT=off: Store 32-bit sig int (no float) coordinates
     GEOPOLY=off: Uses the GeoJSON notation (RFC-7946)
====> Which command line editing library to use:
     READLINES=on: the libreadline from system
     READLINEP=off: the GNU libreadline from ports
     EDITLINE=off: the BSD libedit from ports
====> Where to store temporary file: you have to select exactly one of them
     TS0=off: Always use temporary file
     TS1=on: File by default, change allowed PRAGMA
     TS2=off: Memory by default, change allowed PRAGMA
     TS3=off: Always use memory
====> Which query planner to use, stability or ...: you can only select none or one of them
     STAT3=off: collect histogram data from leftmost column
     STAT4=off: collect histogram data from all columns
===> Use 'make config' to modify these settings
===> The following configuration options are available for readline-8.0.0_1:
     DOCS=off: Build and/or install documentation
===> Use 'make config' to modify these settings
===> The following configuration options are available for libunwind-20170615:
     DOCS=off: Build and/or install documentation
===> Use 'make config' to modify these settings
===> The following configuration options are available for native-binutils-2.33.1,1:
     RELRO=off: enable -z relro in ELF linker by default
     STATIC=off: Build static executables and/or libraries
===> Use 'make config' to modify these settings
===> The following configuration options are available for gmp-6.1.2_1:
     CPU_OPTS=off: Enable assembly optimizations for your CPU
===> Use 'make config' to modify these settings
===> The following configuration options are available for mpfr-4.0.2:
     DOCS=off: Build and/or install documentation
===> Use 'make config' to modify these settings
===> The following configuration options are available for cmake-3.15.5:
     CPACK=off: Enable FreeBSD generator in CPack (experimental)
     DOCS=off: Build and/or install documentation
     MANPAGES=off: Build and/or install manual pages
===> Use 'make config' to modify these settings
===> The following configuration options are available for curl-7.67.0:
     ALTSVC=on: HTTP Alternative Services support
     BROTLI=off: Brotli compression support
     CA_BUNDLE=on: Enable CA bundle for OpenSSL/GnuTLS/mbedTLS
     COOKIES=on: Cookies support
     CURL_DEBUG=off: cURL debug memory tracking
     DEBUG=off: Build with debugging support
     DOCS=off: Build and/or install documentation
     EXAMPLES=off: Build and/or install examples
     IDN=off: International Domain Names support
     IPV6=on: IPv6 protocol support
     METALINK=off: Metalink support
     NTLM=on: NTLM authentication support
     PROXY=on: Proxy support
     PSL=off: Public Suffix List support
     TLS_SRP=off: TLS-SRP (Secure Remote Password) support
====> Options available for the group PROTOCOL
     DICT=on: DICT (RFC 2229) support
     FTP=on: FTP protocol support
     GOPHER=on: Gopher protocol support
     HTTP=on: HTTP/HTTPS support
     HTTP2=on: HTTP/2 support (requires HTTP)
     IMAP=on: IMAP/IMAPS support
     LDAP=off: LDAP protocol support
     LDAPS=off: LDAP protocol over SSL support
     LIBSSH2=off: SCP/SFTP support via libssh2
     POP3=on: POP3/POP3S support
     RTMP=off: RTMP protocol support via librtmp
     RTSP=on: Real Time Streaming Protocol (RTSP) support
     SMB=off: SMB/CIFS support
     SMTP=on: SMTP/SMTPS support
     TELNET=on: Telnet support
     TFTP=on: TFTP support
====> GSSAPI Security API support: you have to select exactly one of them
     GSSAPI_BASE=off: GSSAPI support via base system (needs Kerberos)
     GSSAPI_HEIMDAL=off: GSSAPI support via security/heimdal
     GSSAPI_MIT=off: GSSAPI support via security/krb5
     GSSAPI_NONE=on: Disable GSSAPI support
====> DNS resolving options: you have to select exactly one of them
     CARES=off: Asynchronous DNS resolution via c-ares
     THREADED_RESOLVER=on: Threaded DNS resolver
====> SSL protocol support: you can only select none or one of them
     GNUTLS=off: SSL/TLS support via GnuTLS
     NSS=off: SSL/TLS support via NSS
     OPENSSL=on: SSL/TLS support via OpenSSL
     WOLFSSL=off: SSL/TLS support via wolfSSL
===> Use 'make config' to modify these settings
===> The following configuration options are available for ca_root_nss-3.48:
     ETCSYMLINK=on: Add symlink to /etc/ssl/cert.pem
===> Use 'make config' to modify these settings
===> The following configuration options are available for expat-2.2.8:
     DOCS=off: Build and/or install documentation
===> Use 'make config' to modify these settings
===> The following configuration options are available for python27-2.7.17_1:
     DEBUG=off: Build with debugging support
     IPV6=on: IPv6 protocol support
     LIBFFI=on: Use libffi from ports instead of bundled version
     NLS=off: Enable gettext support for the locale module
     PYMALLOC=on: Enable specialized mallocs
     THREADS=on: Threading support
====> Unicode support: you have to select exactly one of them
     UCS2=off: Enable UCS2 Unicode Strings
     UCS4=on: Enable UCS4 Unicode Strings
===> Use 'make config' to modify these settings
===> The following configuration options are available for python38-3.8.1:
     DEBUG=off: Build with debugging support
     IPV6=on: IPv6 protocol support
     LIBFFI=on: Use libffi from ports instead of bundled version
     NLS=off: Enable gettext support for the locale module
     PYMALLOC=on: Enable specialized mallocs
====> Hash Algorithm (PEP-456): you can only select none or one of them
     FNV=off: Modified Fowler-Noll-Vo Algorithm
     SIPHASH=off: SipHash24 Algorithm
===> Use 'make config' to modify these settings
===> The following configuration options are available for rhash-1.3.5:
     DOCS=off: Build and/or install documentation
===> Use 'make config' to modify these settings
===> The following configuration options are available for libarchive-3.4.0,1:
     LZ4=on: Support lz4 compression via liblz4
     LZO=on: Support lzo compression via liblzo2
     NETTLE=off: Crypto support from Nettle
     OPENSSL=on: Mtree and xar hashes support through openssl
     ZSTD=off: Support zstd compression
===> Use 'make config' to modify these settings
===> The following configuration options are available for lzo2-2.10_1:
     DOCS=off: Build and/or install documentation
     EXAMPLES=off: Build and/or install examples
===> Use 'make config' to modify these settings
===> The following configuration options are available for bison-3.4.2,1:
     DOCS=off: Build and/or install documentation
     EXAMPLES=off: Build and/or install examples
     NLS=off: Native Language Support
===> Use 'make config' to modify these settings

**Comment by fetus-hina** [comment]
Related to #1776 (and old #1706) ?

**Comment by UlasSAYGINIM** [comment]
Thank you for your comment, What is the solution? for libressl version 2.7, it seems patched for freebsd but not patched for libre version 3.x on FreeBSD 12.1 ?

**Comment by fetus-hina** [comment]
I don't know details because I haven't FreeBSD environment.

I checked FreeBSD ports' mirror repository and found this commit https://github.com/freebsd/freebsd-ports/commit/5ad41b14ade66caa44c59c26120690cc9b30a38c  (H2O 2.2.4).

Then, the patch removed when the ports updated to H2O 2.2.5. (https://github.com/freebsd/freebsd-ports/commit/8fa825d520e721442d610e35444842962eb5625d)

However, one part of the patch is **still required**, as described in #1776, I think.
The issue including "LibreSSL 2.7" to the title, but is required for all subsequent versions. (until @kazuho applied the patch and released new v2.2.x.)

If you are installing H2O from FreeBSD ports (and got the error), you may want to inform the FreeBSD ports maintainer. A link to this issue/comment will help to solve build problem.
It seems that `www/h2o-devel`(v2.3β) can be used instead of `www/h2o`(v2.2).

Note: I don't know how to report the problem to the maintainer. Maybe they have their Bug Tracking System.

If you build from _vanilla_ sources, apply the patch below and try building: https://github.com/fetus-hina/h2o-rpm/blob/8064d810915dd6edbba83f3b6f14fdfa71b8e47f/rpmbuild/SOURCES/h2o-libressl-2.7.0.patch

**Comment by utrenkner** [comment]
I am quite sure, @dch (the FreeBSD port maintainer) will notice this issue here.

But of course, he might be on Christmas vacation at the moment...

**Comment by utrenkner** [comment]
Ah, I just found that @UlasSAYGINIM already filed a [bug report at FreeBSD's bugzilla](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242863).

**Comment by UlasSAYGINIM** [comment]
First of All, personally i want to thank you for both of you. because you are amazing and very fast to respond and care the problem. Thank you very much  @fetus-hina and @utrenkner .  specially @fetus-hina , you remember the issue and make the point. amazing and good memory.

Secondly i am replying new problem here too and  i also did in FreeBSD Bugzilla.
Waiting your reply. thanks a lot.

**Comment by UlasSAYGINIM** [comment]
I updated Makefile and created new file named on files/patch-deps_neverbleed-neverbleed.c and saved the patch like this but i got error below. 
patch link is for Freebsd bugzilla  https://bugs.freebsd.org/bugzilla/attachment.cgi?id=210208&action=diff

for information, without this patch , i installed h2o with openssl without problem. but after this patch i dont know does it work or not.


--- deps/neverbleed/neverbleed.c.orig   2019-12-24 22:26:48 UTC
+++ deps/neverbleed/neverbleed.c
@@ -630,7 +630,7 @@ static int sign_stub(struct expbuf_t *buf)
return 0;
  }

-#if !OPENSSL_1_1_API
+#if !OPENSSL_1_1_API && !defined(LIBRESSL_VERSION_NUMBER)
static void RSA_get0_key(const RSA *rsa, const BIGNUM **n, const BIGNUM **e, const BIGNUM **d)
  {


######### ERROR with Patch #########

--- CMakeFiles/h2o.dir/deps/neverbleed/neverbleed.c.o ---
/usr/ports/www/h2o/work/h2o-2.2.6/deps/neverbleed/neverbleed.c:635:13: error: static declaration of 'RSA_get0_key' follows non-static declarati                                                                                              on
static void RSA_get0_key(const RSA *rsa, const BIGNUM **n, const BIGNUM **e, const BIGNUM **d)
            ^
/usr/local/include/openssl/rsa.h:399:6: note: previous declaration is here
void RSA_get0_key(const RSA *r, const BIGNUM **n, const BIGNUM **e,
     ^
/usr/ports/www/h2o/work/h2o-2.2.6/deps/neverbleed/neverbleed.c:650:12: error: static declaration of 'RSA_set0_key' follows non-static declarati                                                                                              on
static int RSA_set0_key(RSA *rsa, BIGNUM *n, BIGNUM *e, BIGNUM *d)
           ^
/usr/local/include/openssl/rsa.h:401:5: note: previous declaration is here
int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d);
    ^
/usr/ports/www/h2o/work/h2o-2.2.6/deps/neverbleed/neverbleed.c:666:13: error: static declaration of 'RSA_set_flags' follows non-static declarat                                                                                              ion
static void RSA_set_flags(RSA *r, int flags)
            ^
/usr/local/include/openssl/rsa.h:409:6: note: previous declaration is here
void RSA_set_flags(RSA *r, int flags);
     ^
3 errors generated.
*** [CMakeFiles/h2o.dir/deps/neverbleed/neverbleed.c.o] Error code 1

make[4]: stopped in /usr/ports/www/h2o/work/.build
1 error

make[4]: stopped in /usr/ports/www/h2o/work/.build
*** [CMakeFiles/h2o.dir/all] Error code 2

make[3]: stopped in /usr/ports/www/h2o/work/.build
1 error

make[3]: stopped in /usr/ports/www/h2o/work/.build
*** [all] Error code 2

make[2]: stopped in /usr/ports/www/h2o/work/.build
1 error

make[2]: stopped in /usr/ports/www/h2o/work/.build
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/www/h2o
*** Error code 1

Stop.
make: stopped in /usr/ports/www/h2o

**Comment by UlasSAYGINIM** [comment]
New ERROR here with another patch  https://bugs.freebsd.org/bugzilla/attachment.cgi?id=210225&action=diff

--- CMakeFiles/h2o.dir/deps/neverbleed/neverbleed.c.o ---
/usr/ports/www/h2o/work/h2o-2.2.6/deps/neverbleed/neverbleed.c:635:13: error: st                                                             atic declaration of 'RSA_get0_key' follows non-static declaration
static void RSA_get0_key(const RSA *rsa, const BIGNUM **n, const BIGNUM **e, con                                                             st BIGNUM **d)
            ^
/usr/local/include/openssl/rsa.h:399:6: note: previous declaration is here
void RSA_get0_key(const RSA *r, const BIGNUM **n, const BIGNUM **e,
     ^
/usr/ports/www/h2o/work/h2o-2.2.6/deps/neverbleed/neverbleed.c:650:12: error: st                                                             atic declaration of 'RSA_set0_key' follows non-static declaration
static int RSA_set0_key(RSA *rsa, BIGNUM *n, BIGNUM *e, BIGNUM *d)
           ^
/usr/local/include/openssl/rsa.h:401:5: note: previous declaration is here
int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d);
    ^
/usr/ports/www/h2o/work/h2o-2.2.6/deps/neverbleed/neverbleed.c:666:13: error: st                                                             atic declaration of 'RSA_set_flags' follows non-static declaration
static void RSA_set_flags(RSA *r, int flags)
            ^
/usr/local/include/openssl/rsa.h:409:6: note: previous declaration is here
void RSA_set_flags(RSA *r, int flags);
     ^
--- CMakeFiles/h2o.dir/deps/picotls/lib/picotls.c.o ---
--- CMakeFiles/h2o.dir/deps/neverbleed/neverbleed.c.o ---
3 errors generated.
*** [CMakeFiles/h2o.dir/deps/neverbleed/neverbleed.c.o] Error code 1

make[4]: stopped in /usr/ports/www/h2o/work/.build
--- CMakeFiles/h2o.dir/deps/picotls/lib/picotls.c.o ---
[ 60%] Building C object CMakeFiles/h2o.dir/deps/picotls/lib/picotls.c.o
/usr/bin/cc  -I/usr/ports/www/h2o/work/h2o-2.2.6/deps/mruby/include -I/usr/ports                                                             /www/h2o/work/h2o-2.2.6/deps/mruby-input-stream/src -I/usr/ports/www/h2o/work/h2                                                             o-2.2.6/include -I/usr/ports/www/h2o/work/h2o-2.2.6/deps/cloexec -I/usr/ports/ww                                                             w/h2o/work/h2o-2.2.6/deps/brotli/enc -I/usr/ports/www/h2o/work/h2o-2.2.6/deps/go                                                             lomb/usr/ports/www/h2o/work/h2o-2.2.6/deps/libgkc -I/usr/ports/www/h2o/work/h2o-                                                             2.2.6/deps/libyrmcds -I/usr/ports/www/h2o/work/h2o-2.2.6/deps/klib -I/usr/ports/                                                             www/h2o/work/h2o-2.2.6/deps/neverbleed -I/usr/ports/www/h2o/work/h2o-2.2.6/deps/                                                             picohttpparser -I/usr/ports/www/h2o/work/h2o-2.2.6/deps/picotest -I/usr/ports/ww                                                             w/h2o/work/h2o-2.2.6/deps/yaml/include -I/usr/ports/www/h2o/work/h2o-2.2.6/deps/                                                             yoml -I/usr/local/include -I/usr/ports/www/h2o/work/h2o-2.2.6/deps/picotls/deps/                                                             cifra/src/ext -I/usr/ports/www/h2o/work/h2o-2.2.6/deps/picotls/deps/cifra/src -I                                                             /usr/ports/www/h2o/work/h2o-2.2.6/deps/picotls/deps/micro-ecc -I/usr/ports/www/h                                                             2o/work/h2o-2.2.6/deps/picotls/include -O2 -g -Wall -Wno-unused-value -Wno-unuse                                                             d-function -O2 -pipe -fno-strict-aliasing -march=native  -fstack-protector-stron                                                             g -DH2O_ROOT="/usr/local" -DH2O_CONFIG_PATH="etc/h2o.conf" -pthread -O2 -pipe -f                                                             no-strict-aliasing -march=native  -fstack-protector-strong   -DH2O_USE_LIBUV=0 -                                                             DH2O_USE_BROTLI=1 -DH2O_USE_MRUBY=1 -DH2O_USE_PICOTLS=1 -o CMakeFiles/h2o.dir/de                                                             ps/picotls/lib/picotls.c.o   -c /usr/ports/www/h2o/work/h2o-2.2.6/deps/picotls/l                                                             ib/picotls.c
1 error

make[4]: stopped in /usr/ports/www/h2o/work/.build
*** [CMakeFiles/h2o.dir/all] Error code 2

make[3]: stopped in /usr/ports/www/h2o/work/.build
1 error

make[3]: stopped in /usr/ports/www/h2o/work/.build
*** [all] Error code 2

make[2]: stopped in /usr/ports/www/h2o/work/.build
1 error

make[2]: stopped in /usr/ports/www/h2o/work/.build
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/www/h2o
*** Error code 1

Stop.
make: stopped in /usr/ports/www/h2o

**Comment by dch** [comment]
patch was included in www/h2o ports last year

**Comment by dch** [comment]
my bad, the patch I included no longer works

**Comment by UlasSAYGINIM** [comment]
Thank you for update. when necessary patch is added than i can try.

**Comment by UlasSAYGINIM** [comment]
Hello, I tested Freebsd 13 with h2o web server.
i got success. i think it should work Freebsd 12.1 too. i couldnt try it. sorry for that. but i will look if i can try.

installation notes below.

====> Compressing man pages (compress-man)
===> Staging rc.d startup script(s)
===>  Installing for h2o-2.2.6
===>  Checking if h2o is already installed
===>   Registering installation for h2o-2.2.6
Installing h2o-2.2.6...
===> SECURITY REPORT:
      This port has installed the following files which may act as network
      servers and may therefore pose a remote security risk to the system.
/usr/local/bin/h2o
/usr/local/lib/libh2o.so.0.13.6
/usr/local/lib/libh2o-evloop.so.0.13.6

      If there are vulnerabilities in these programs there may be a security
      risk to the system. FreeBSD makes no guarantee about the security of
      ports included in the Ports Collection. Please type 'make deinstall'
      to deinstall the port if this is a concern.

      For more information, and contact details about the security
      status of this software, see the following webpage:
https://github.com/h2o/h2o

**Comment by dch** [comment]
thanks Ulaş. I'm confused here, did you build this from ports with LibreSSL *and* any extra patches? or just what we have in tree today?

**Comment by UlasSAYGINIM** [comment]
I build h2o web server on freebsd 13 with port tree.
I didnt use any patches, just regularly use port installation after vanilla install of freebsd 13.
I used make.conf default versions to set libressl as default ssl port.

is it enough information for you @dch ? or do you need anything else?

**Comment by dch** [comment]
that's awesome  - it means we can close this :-) thanks for the update
