### ISSUE TITLE
Built with mruby fails since 1.7.x on FreeBSD 9.3

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#869]
As I accidentally updated my local 1.6.3 version with the latest FreeBSD package (1.7.1), I lost support for mruby (the standard package comes without mruby). Thus, I wanted to built it myself, but got this error:
```
===>  Building for h2o-1.7.1
Scanning dependencies of target mruby
(in /var/ports/usr/ports/www/h2o/work/h2o-1.7.1/deps/mruby)
checking for struct stat.st_birthtimespec in sys/stat.h... rake aborted!
The compiler failed to generate an executable file.
You have to install development tools first.
Rakefile:26:in `load'
```
I tried various revisions: The problem exists since 1.7.x (I tried 1.7.0, 1.7.1 via FreeBSD ports and also the very latest Github sources). I can still build 1.6.3 with mruby. So what tools am I missing here? And should their existence be checked earlier?

**Comment by syohex** [comment]
It looks [mruby-file-stat](https://github.com/ksss/mruby-file-stat) configuration is failed.
However I cannot reproduce this issue on my FreeBSD 9.3 with Ruby 2.3.0. Which ruby version did you use ?

**Comment by kazuho** [comment]
@ksss As the author of mruby-file-stat, do you know anything about this error?

**Comment by ksss** [comment]
Seems [mruby-file-stat](https://github.com/ksss/mruby-file-stat) issue.

I've encountered a similar problem.
This issue can reproduce when failed in CRuby [mkmf](http://docs.ruby-lang.org/en/trunk/MakeMakefile.html).
mruby-file-stat is checking your environment by CRuby mkmf.
But, old CRuby mkmf has some bugs like [this](https://github.com/ksss/mruby-file-stat/blob/cbec1f23ada1307323d6191b4126a687de487901/mrbgem.rake#L3-L11).

What did you use ruby version?
And do you have `mkmf.log` after build?
And can you try to add option `--trace` to `rake` or `minirake`?
(I don't know h2o build system.)

**Comment by utrenkner** [comment]
Thanks for looking into this!
The version of the ruby tools should not be the cause of the problem - I use exactly the same versions on a FreeBSD 10.2 server and there I can built any version of h2o with mruby:
```
ruby-2.2.4,1                   Object-oriented interpreted scripting language
ruby22-gems-2.6.2              Package management framework for the Ruby language
rubygem-rake-10.5.0            Ruby Make
```
When I try to build the latest FreeBSD port (1.7.1) on my FreeBSD 9.3 Laptop I get this `mkmf.log` output:
```
"cc -o conftest -I/usr/local/include/ruby-2.2//amd64-freebsd9 -I/usr/local/include/ruby-2.2//ruby/backward -I/usr/local/include/ruby-2.2/ -I. -I/usr/local/include -isystem /usr/local/include   -O2 -pipe -isystem /usr/local/include -fstack-protector -fno-strict-aliasing -fPIC conftest.c  -L. -L/usr/local/lib -L.   -L/usr/local/lib -fstack-protector -rdynamic     -lruby22  -lexecinfo -lprocstat -lcrypt -lm -lpthread -L/usr/local/lib  -lc"
/usr/local/lib/libruby22.so: undefined reference to `procstat_getvmmap@FBSD_1.3'
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by syohex** [comment]
Does your libprocstat contains `procstat_getvmmap` ? You can check it by

```
% nm /usr/lib/libprocstat.a | grep procstat_getvmmap
```

And did you update userland programs ? `procstat_getvmmap` was introduced at FreeBSD 9.2. So if you did not update userland programs, you might get such error.

**Comment by utrenkner** [comment]
@syohex 

```
# nm /usr/lib/libprocstat.a | grep procstat_getvmmap
0000000000001330 T procstat_getvmmap
```

I always use freebsd-update to stay uptodate (currently 9.3-RELEASE-p39). I also forced an upgrade of all packages (from the official repository). One possibly interesting thing: While this problem exists in my local webserver jail, I was able to build h2o with mruby on the host system itself (running the exact same software versions). However, as the same setup works on the 10.3 server, I do not really believe that this is a clue...

**Comment by syohex** [comment]
Is jail environment also updated ?

**Comment by ksss** [comment]
I found similar issue https://bugs.ruby-lang.org/issues/10954 (Japanese)
But, this issue looks like backported to CRuby 2.2. hmm...

So, you can also choose this patch if you want to just build.(You will not be able to use a few mruby methods)

```patch
diff --git a/deps/mruby-file-stat/mrbgem.rake b/deps/mruby-file-stat/mrbgem.rake
index 423495e..55e66b2 100644
--- a/deps/mruby-file-stat/mrbgem.rake
+++ b/deps/mruby-file-stat/mrbgem.rake
@@ -13,19 +13,6 @@ end
 build_extconf = lambda do |fn|
   return if File.exist?(fn)

-  # TODO
-  # if open this block
-  # raise error: redefinition of 'struct timespec'
-  # in windows
-  if RUBY_PLATFORM !~ /mingw|mswin/
-    have_struct_member "struct stat", "st_birthtimespec", "sys/stat.h"
-    have_struct_member "struct stat", "st_blksize", "sys/stat.h"
-    have_struct_member "struct stat", "st_blocks", "sys/stat.h"
-
-    have_func "lstat", "sys/stat.h"
-    have_func "getgroups", "unistd.h"
-  end
-
   create_header fn
 end
```

**Comment by kazuho** [comment]
@ksss Thank you for the suggestion.

If that is the case, I'd like to consider stop using rake for building mruby-file-stat with H2O, and switch to minirake, since by doing so, we no longer will need to depend on the development files of ruby.

**Comment by utrenkner** [comment]
Thanks to all of you for your help.

@syohex I always ran freebsd-update also for this jail.

@ksss Even though I do not read Japanese, I saw that it relates to a FreeBSD 9.1 system, which according to @syohex does not have `procstat_getvmmap`. My understanding is, that anything 9.2 and later should have this function and thus this problem would probably not trigger.

To better identify the problem I installed a clean 9.3 jail on my laptop, updated everything - and there the problem does not exist. Thus it seem to stem from freebsd-update'ing the jail over several minor versions. Something must have gone wrong, there. This probably is a rather unique problem and thus I would suggest to close this issue. Nevertheless, if you would like me to further test certain diffs, please let me know.

Again, many thanks for taking the time to help. I really appreciate it.
