### ISSUE TITLE
file.send-brotli build error

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#815]
The build following error is reported on FreeBSD 10.3 after the new brotli support was added.

```
...
[ 38%] Building C object CMakeFiles/h2o.dir/lib/http2/scheduler.c.o
[ 38%] Building C object CMakeFiles/h2o.dir/lib/http2/stream.c.o
[ 38%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/api.c.o
[ 41%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/dumper.c.o
[ 41%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/emitter.c.o
[ 41%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/loader.c.o
[ 41%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/parser.c.o
[ 43%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/reader.c.o
[ 43%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/scanner.c.o
[ 43%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/writer.c.o
[ 43%] Building CXX object CMakeFiles/h2o.dir/deps/brotli/enc/backward_references.cc.o
[ 46%] Building CXX object CMakeFiles/h2o.dir/deps/brotli/enc/block_splitter.cc.o
[ 46%] Building CXX object CMakeFiles/h2o.dir/deps/brotli/enc/brotli_bit_stream.cc.o
/tmp/h2o/deps/brotli/enc/brotli_bit_stream.cc:337:33: error: use of undeclared identifier 'malloc'; did you mean 'valloc'?
      static_cast<HuffmanTree*>(malloc(max_tree_size * sizeof(HuffmanTree)));
                                ^~~~~~
                                valloc
/usr/include/unistd.h:583:7: note: 'valloc' declared here
void    *valloc(size_t);                        /* obsoleted by malloc() */
         ^
/tmp/h2o/deps/brotli/enc/brotli_bit_stream.cc:398:3: error: use of undeclared identifier 'free'
  free(tree);
  ^
2 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /tmp/h2o
*** Error code 1

Stop.
make[1]: stopped in /tmp/h2o
*** Error code 1

Stop.
make: stopped in /tmp/h2o
```

**Comment by kazuho** [comment]
Thank you for noticing the issue.  Fixed in the commit above.

**Comment by Tintinabula** [comment]
Thanks. h2o builds on FreeBSD 10.3 and pre-compressed Brotli (.br) files are being served to compatible clients. Brotli verified with Firefox v44.0.2 on Linux. Non-brotli compatible clients Like Google Chrome v48.0.2 are receiving the pre-compressed gzip (.gz) files as expected. Google Chrome v49 should have Brotli support when it is released on Feb 29th.
