### ISSUE TITLE
ENGINE API deprecated

### ISSUE THREAD

**Issue by Leodmanx2** [h2o/h2o#3398]
Engines were deprecated in OpenSSL 3.0 in favour of Providers.
Support was fully removed from LibreSSL in version 3.9.0.

My build on OpenBSD 7.5 is failing because the following `ENGINE_*` functions are undeclared and h2o currently cannot be configured to not use the Neverbleed engine.
https://github.com/h2o/h2o/blob/16b13eee8ad7895b4fe3fcbcabee53bd52782562/deps/neverbleed/neverbleed.c#L2223-L2232

**Comment by botovq** [comment]
fwiw, the OpenBSD port was patched to work without ENGINE (it has since been removed since dnsdist switched to quiche): https://github.com/openbsd/ports/tree/c1521c4eb969ddf29306117ea125802a2644e734/www/h2o/patches

This still uses API considered deprecated by OpenSSL 3, though.

**Comment by calvin2021y** [comment]
@kazuho any plan to merge this or close it?

**Comment by fetus-hina** [comment]
OpenSSL ENGINEs have been [deprecated in RHEL 10](https://docs.redhat.com/ja/documentation/red_hat_enterprise_linux/10-beta/html/10.0_beta_release_notes/deprecated-features#deprecated-features-security).
I have not tested this on RHEL 10 beta yet, but at least on the current CentOS 10-stream, the build actually fails.

<details>
<summary>Error messages</summary>

```
/h2o/deps/neverbleed/neverbleed.c: In function 'daemon_main':
/h2o/deps/neverbleed/neverbleed.c:2076:23: error: implicit declaration of function 'ENGINE_by_id' [-Wimplicit-function-declaration]
 2076 |         ENGINE *qat = ENGINE_by_id("qatengine");
      |                       ^~~~~~~~~~~~
/h2o/deps/neverbleed/neverbleed.c:2076:23: error: initialization of 'ENGINE *' {aka 'struct engine_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
/h2o/deps/neverbleed/neverbleed.c:2077:28: error: implicit declaration of function 'ENGINE_init' [-Wimplicit-function-declaration]
 2077 |         if (qat != NULL && ENGINE_init(qat)) {
      |                            ^~~~~~~~~~~
/h2o/deps/neverbleed/neverbleed.c:2078:18: error: implicit declaration of function 'ENGINE_set_default_RSA' [-Wimplicit-function-declaration]
 2078 |             if (!ENGINE_set_default_RSA(qat))
      |                  ^~~~~~~~~~~~~~~~~~~~~~
/h2o/deps/neverbleed/neverbleed.c: In function 'neverbleed_init':
/h2o/deps/neverbleed/neverbleed.c:2236:27: error: implicit declaration of function 'ENGINE_new' [-Wimplicit-function-declaration]
 2236 |         if ((nb->engine = ENGINE_new()) == NULL || !ENGINE_set_id(nb->engine, "neverbleed") ||
      |                           ^~~~~~~~~~
/h2o/deps/neverbleed/neverbleed.c:2236:25: error: assignment to 'ENGINE *' {aka 'struct engine_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
 2236 |         if ((nb->engine = ENGINE_new()) == NULL || !ENGINE_set_id(nb->engine, "neverbleed") ||
      |                         ^
/h2o/deps/neverbleed/neverbleed.c:2236:53: error: implicit declaration of function 'ENGINE_set_id' [-Wimplicit-function-declaration]
 2236 |         if ((nb->engine = ENGINE_new()) == NULL || !ENGINE_set_id(nb->engine, "neverbleed") ||
      |                                                     ^~~~~~~~~~~~~
/h2o/deps/neverbleed/neverbleed.c:2237:14: error: implicit declaration of function 'ENGINE_set_name' [-Wimplicit-function-declaration]
 2237 |             !ENGINE_set_name(nb->engine, "privilege separation software engine") || !ENGINE_set_RSA(nb->engine, rsa_method)
      |              ^~~~~~~~~~~~~~~
/h2o/deps/neverbleed/neverbleed.c:2237:86: error: implicit declaration of function 'ENGINE_set_RSA' [-Wimplicit-function-declaration]
 2237 |             !ENGINE_set_name(nb->engine, "privilege separation software engine") || !ENGINE_set_RSA(nb->engine, rsa_method)
      |                                                                                      ^~~~~~~~~~~~~~
/h2o/deps/neverbleed/neverbleed.c:2239:17: error: implicit declaration of function 'ENGINE_set_EC' [-Wimplicit-function-declaration]
 2239 |             || !ENGINE_set_EC(nb->engine, ecdsa_method)
      |                 ^~~~~~~~~~~~~
/h2o/deps/neverbleed/neverbleed.c:2245:9: error: implicit declaration of function 'ENGINE_add' [-Wimplicit-function-declaration]
 2245 |         ENGINE_add(nb->engine);
      |         ^~~~~~~~~~
/h2o/deps/neverbleed/neverbleed.c:2266:9: error: implicit declaration of function 'ENGINE_free' [-Wimplicit-function-declaration]
 2266 |         ENGINE_free(nb->engine);
      |         ^~~~~~~~~~~
At top level:
cc1: note: unrecognized command-line option '-Wno-nullability-completeness' may have been intended to silence earlier diagnostics
make[2]: *** [CMakeFiles/h2o.dir/build.make:2377: CMakeFiles/h2o.dir/deps/neverbleed/neverbleed.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/h2o/src/main.c: In function 'listener_setup_ssl':
/h2o/src/main.c:2201:13: warning: 'PEM_read_bio_DHparams' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 2201 |             DH *dh = PEM_read_bio_DHparams(bio, NULL, NULL, NULL);
      |             ^~
In file included from /usr/include/openssl/ssl.h:37,
                 from /h2o/src/main.c:69:
/usr/include/openssl/pem.h:473:1: note: declared here
  473 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, DHparams, DH)
      | ^~~~~~~~~~~~~~~~~~~
/h2o/src/main.c:2210:13: warning: 'DH_free' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 2210 |             DH_free(dh);
      |             ^~~~~~~
In file included from /h2o/src/main.c:67:
/usr/include/openssl/dh.h:207:28: note: declared here
  207 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
At top level:
cc1: note: unrecognized command-line option '-Wno-nullability-completeness' may have been intended to silence earlier diagnostics
make[1]: *** [CMakeFiles/Makefile2:478: CMakeFiles/h2o.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
</details>

To build h2o on RHEL 10, I need to either statically link OpenSSL or replace the code that uses ENGINEs.
I suspect that other distributions, such as Ubuntu and Debian, will adopt a similar change in the near future.

Here is the Dockerfile I used to reproduce the error:
<details>
<summary>Dockerfile</summary>

```docker
FROM quay.io/centos/centos:stream10
RUN dnf update -y && \
    dnf install -y \
        cmake \
        gcc-c++ \
        git \
        make \
        openssl \
        openssl-devel \
        perl \
        zlib-ng-compat \
        zlib-ng-compat-devel \
      && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Use static built OpenSSL
# RUN mkdir /openssl && \
#     cd /openssl && \
#     curl -fsSL 'https://github.com/openssl/openssl/releases/download/openssl-3.2.3/openssl-3.2.3.tar.gz' | \
#         tar -zxf - --strip-components=1 \
#       && \
#     ./config --release --with-rand-seed=devrandom \
#         no-asm \
#         no-comp \
#         no-shared \
#         no-tests \
#         no-zlib \
#         CFLAGS="-O2 -march=x86-64-v3 -mtune=generic -DNDEBUG" \
#         CXXFLAGS="-O2 -march=x86-64-v3 -mtune=generic -DNDEBUG" \
#       && \
#       make -j$(nproc) && \
#       make install_sw && \
#     cd / && \
#     rm -rf /openssl

RUN git clone --depth=1 --recursive https://github.com/h2o/h2o.git /h2o && \
    cd /h2o && \
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_FLAGS="-O2 -march=x86-64-v3 -mtune=generic -fPIE -pie" \
        -DCMAKE_CXX_FLAGS="-O2 -march=x86-64-v3 -mtune=generic -fPIE -pie" \
        -DWITH_MRUBY=off \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        . \
      && \
    make -j$(nproc) && \
    make install && \
    cd / && \
    rm -rf /h2o

RUN h2o -v
CMD ["/usr/local/bin/h2o"]
```
</details>

When I remove the comments related to OpenSSL, the build succeeds with static linking.
