### ISSUE TITLE
FreeBSD 11.0 hiredis build error

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#1317]
Building the latest H2O errors out on hiredis. Last time we built H2O was before hiredis was added.

OS: FreeBSD 11.0-RELEASE , patched

```
FreeBSDzfs:  cmake -DCMAKE_INSTALL_PREFIX=/usr/local 
     -DCMAKE_CXX_FLAGS="-Wall -ggdb3 -O2 
     -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wformat 
     -Werror=format-security -std=c++0x -fvisibility=hidden" 
     -DCMAKE_C_FLAGS="-Wall -ggdb3 -O2 -fstack-protector-all 
     -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security 
     -fvisibility=hidden" -DWITH_BUNDLED_SSL=on 
     -DWITH_PICOTLS=on -DWITH_MRUBY=on . && 
     make && make install && echo OKOKOKOKKOKO

-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/libssl.so;/usr/lib/libcrypto.so (found version "1.0.2k") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.8") 
-- Found LIBUV: /usr/local/lib/libuv.so  
-- libuv found but ignored; is too old
-- Could NOT find WSLAY (missing:  WSLAY_LIBRARIES WSLAY_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/h2o
Scanning dependencies of target libh2o-evloop
[  0%] Building C object CMakeFiles/libh2o-evloop.dir/deps/cloexec/cloexec.c.o
[  0%] Building C object CMakeFiles/libh2o-evloop.dir/deps/hiredis/async.c.o
[  1%] Building C object CMakeFiles/libh2o-evloop.dir/deps/hiredis/hiredis.c.o
[  1%] Building C object CMakeFiles/libh2o-evloop.dir/deps/hiredis/net.c.o
/tmp/h2o/deps/hiredis/net.c:435:29: error: use of undeclared identifier 'AF_LOCAL'
    if (redisCreateSocket(c,AF_LOCAL) < 0)
                            ^
/tmp/h2o/deps/hiredis/net.c:460:21: error: use of undeclared identifier 'AF_LOCAL'
    sa.sun_family = AF_LOCAL;
                    ^
2 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /tmp/h2o
*** Error code 1

Stop.
make[1]: stopped in /tmp/h2o
*** Error code 1

Stop.
make: stopped in /tmp/h2o

root@FreeBSDzfs:  

```

**Comment by Tintinabula** [comment]
The hiredis build error is caused by AF_LOCAL not being defined. According to the hiredis github page this bug was fixed and then perhaps broken again in later code.

There is an "If" check in net.h which is looking for "__sun" machines, but not OSX or FreeBSD. 

A simple hack is to remove the "If" check  and endif lines so AF_LOCAL is always defined and H2O builds correctly on FreeBSD v11.1 .

```
vi /tmp/h2o/deps/hiredis/net.h

-   #if defined(__sun)
    #define AF_LOCAL AF_UNIX
-   #endif
```

**Comment by deweerdt** [comment]
I see hiredis has the following PR pending: https://github.com/redis/hiredis/pull/525

**Comment by dch** [comment]
@Tintinabula see https://github.com/h2o/h2o/pull/1426 I believe it addresses your issue?

**Comment by tw-bert** [comment]
Solved my issue on AIX as well. Redis 4.0.5.

**Comment by Tintinabula** [comment]
The hiredis build error no longer triggers so I will close this ticket.
